#!/bin/bash
#
DB_NAME=""
DB_USER=""
DB_PASS=""
DB_HOST="mysql"
DB_PORT="3306"
DB_BAK_PATH="/root/mysql/backup"


mysqldump -h${DB_HOST} -u${DB_USER} -p${DB_PASS} -P${DB_PORT} ${DB_NAME} > ${DB_BAK_PATH}/${DB_NAME}_`date "+%Y-%m-%d"`.sql


cd ${DB_BAK_PATH}
tar zcf ${DB_NAME}_`date "+%Y-%m-%d"`.sql.tar.gz ${DB_NAME}_`date "+%Y-%m-%d"`.sql
rm -f ${DB_BAK_PATH}/${DB_NAME}_`date "+%Y-%m-%d"`.sql
#cp ${DB_BAK_PATH}/${DB_NAME}_`date "+%Y-%m-%d"`.sql.tar.gz /tmp/ossfs/db_backup/${DB_NAME}_sql_bak/

find ${DB_BAK_PATH}/ -mtime +7 -name "*.tar.gz" -exec rm -rf {} \;
